# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50860ddc4f993ef7e46b0b6a828b56ba214e7d4aa86cb9b463310b9c59b0da4f1a14b60c4d8c9d56fd8db5060bf91170ead8e0c9894aaa8a3fe7892f91159121

test:
  secret_key_base: 2b35783d712f1e7cd2ea58aebca526fcb73b8cbc610d07bb41a026915fdefd170d09b5b424fa0e87ac90bd0a59e98e197257d97fc613a4ef1d76fe5f2afb255d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
